# playbooks/secret_update
pull_secret:

# roles/shared
subscription_source:
custom_catalog:
custom_catalog_image:
my_company:

# roles/bpfman
bpfman_version:

# roles/cluster_network
new_hostPrefix:

# playbooks/troubleshoot
# Set the ovs syslog:<log_level> value. Log levels are off, emer, err, warn, info, or dbg
ovs_syslog_level: dbg
