---
- name: Replace Pull Secret
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Delete existing pull-secret from openshift-config namespace
      ansible.builtin.command: oc delete secret pull-secret -n openshift-config

    - name: Add the new pull-secret to openshift-config namespace
      ansible.builtin.command: oc create secret generic pull-secret -n openshift-config \
        --from-file=.dockerconfigjson="{{ pull_secret }}" --type=kubernetes.io/dockerconfigjson